/**
 * Emit the Sketch class universe as a TS file Tailwind's scanner reads —
 * docs/sketch-design.md §7's safelist, generated (never hand-edited) from
 * the same tables the exhaustive tests enumerate.
 *
 * Usage: tsx scripts/gen-safelist.ts <output-path>
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { classUniverse } from "../src/emit.js";
import { defaultTheme } from "../src/theme.js";

const out = process.argv[2];
if (!out) {
  console.error("usage: tsx scripts/gen-safelist.ts <output-path>");
  process.exit(1);
}

const classes = classUniverse(defaultTheme);
const content = [
  "// AUTO-GENERATED by @drafting/sketch-core scripts/gen-safelist.ts — DO NOT EDIT.",
  "// Tailwind's scanner reads these names so the Sketch canvas (which composes",
  "// classes at runtime via toElement) renders inside Drafting. Fixed-px",
  "// arbitrary values are excluded — the canvas shims those to inline style.",
  "// Regenerate when the alphabet or theme changes: pnpm gen:sketch-safelist",
  `export const SKETCH_SAFELIST = "${classes.join(" ")}";`,
  "",
].join("\n");

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, content);
console.error(`[gen-safelist] wrote ${out} (${classes.length} classes)`);
